### ISSUE TITLE
Use @tomek somewhere on the site

### ISSUE THREAD

**Issue by bmispelon** [djangounderthehood/duh-web#17]
https://pypi.python.org/pypi/tomek/0.2

**Comment by asendecka** [comment]
:bomb: :fire: :boom:

**Comment by asendecka** [comment]
I wonder if it will ever happen 😢 We need this!

**Comment by olasitarska** [comment]
I think Tomek missed the opportunity when building the lottery app!

**Comment by asendecka** [comment]
That's a shame.

**Comment by agagata** [comment]
@bmispelon won! ✨ 💐
