### ISSUE TITLE
Question about less compilation

### ISSUE THREAD

**Issue by KatherineMichel** [djangounderthehood/duh-web#30]
Hi, I'm running this on a local server for fun, but getting this error. Can anyone give me any guidance for how the less files are being installed/compiled? I did npm install -g less but still not working. 
![screen shot 2016-05-04 at 11 44 38 pm](https://cloud.githubusercontent.com/assets/4193054/15053627/208df066-12c9-11e6-82cf-28cf375d9582.png)
Thank you

**Comment by oinopion** [comment]
Hi @KatherineMichel, because we use `less` for smarter stylesheets, you need to have `node` installed on your system and then do `npm install` in the main repo directory.

I've added this now to the README, sorry for being so lazy 😉

**Comment by oinopion** [comment]
Closing this for now, but don't hesitate to reopen if it's not working for you.

**Comment by KatherineMichel** [comment]
Worked perfectly. Thank you @oinopion !
